### ISSUE TITLE
Install Django extensions

### ISSUE THREAD

**Issue by chongyangye** [diego04/cmput410-project#13]
Hi guys, for post I use UUID as the post Id, so please type "pip install django-extensions
" to install it, after you pull and the installation done, it should be good to post. If you have other error like no module extensions, go to settings.py

**Comment by kevindeasis** [comment]
this one too... pip install django-nose

**Comment by kevindeasis** [comment]
pip install coverage

**Comment by kevindeasis** [comment]
pip install factory_boy

**Comment by gmeyer1** [comment]
List of required plugins is in wiki.
