### ISSUE TITLE
Login bug

### ISSUE THREAD

**Issue by chongyangye** [diego04/cmput410-project#19]
just want to remind you guys there is a bug on login part, maybe you can not login if you are the author, i will fix it later

**Comment by chongyangye** [comment]
it's been fixed and I will push this after I finish post part, for know you can use user 'admin' pwd' admin 'to run

**Comment by kevindeasis** [comment]
This is not a bug. this is a user, an administrator needs to approve a newly register user to login to the site.

**Comment by chongyangye** [comment]
ok,great, i will not touch that

**Comment by jasonqi77** [comment]
how can the admin approve the new user? I cannot find the way to do it

**Comment by kevindeasis** [comment]
youd have to login as administrator in /admin  then click an author and in there profile check the accept or somthing

**Comment by gmeyer1** [comment]
No bug, users just needed to approved.
