### ISSUE TITLE
problem runserver

### ISSUE THREAD

**Issue by chongyangye** [diego04/cmput410-project#2]
I saw in os file you have the problem of No module named django.core.management, after that you modify the manage.py file, what did you do in this modification?

**Comment by kevindeasis** [comment]
change the she bang line in manage.py :http://stackoverflow.com/questions/6049933/django-import-error-no-module-named-core-management

**Comment by chongyangye** [comment]
I tried change the she bang line in manage.py, and reinstall django, they both didn't work. The TA also has no idea about this, finally I delete the virtualenv_ file and create a new virtual environment with the same name, then install django under the virtual environment I created, it works. If you guys have the same problem, don't waste time on this, just re-create a virtual environment

**Comment by kevindeasis** [comment]
So, is it not working again?

**Comment by chongyangye** [comment]
no, I just put it here let other people know this

**Comment by kevindeasis** [comment]
Ok great thanks.
