### ISSUE TITLE
Next Sprint

### ISSUE THREAD

**Issue by kevindeasis** [diego04/cmput410-project#37]
Off the top of my head they are:

TDD
Basic Auth
Github rss?
connecting with at least two other groups.
Refactoring models
Testing
Fixing html and css, including links
Stream posts based on follow or friend status

**Comment by gmeyer1** [comment]
I can look into either auth or Github integration if we'd like. Has anything been claimed in terms of tasks so far?

**Comment by kevindeasis** [comment]
None has been taken. Basic auth is all yours
